### ISSUE TITLE
Product Management

### ISSUE THREAD

**Issue by dguglielmi-git** [dguglielmi-git/innovandoliving-ts#1]
## Description
We need to add a Product Management section so that users will be able to manage the list of products available on the site. Additionally, we should include the Categories Management section within the same view.

## Acceptance Criteria
- **Product Management View** 🎁 
  - [x] Card indicating Total Categories and Total Products: both should indicate the total amount of categories and products in the database.
  - [x] Search bar to filter by products
    - [x] Search bar functionality, should filter the products after typing
  - [x] Every row in the product table should have two buttons, Edit (✏) and Remove (🪣), both have to show a tooltip when hovering. 
- **Category List Section** 🗒 
  - [x] **Add Category** button: open a dialog to add a category, it's not allowed to modify categories, only add and remove.
  - [x] Category List Title
  - [x] Category List that lists all the categories stored in the database
  - [x] Table should have a fixed size of 4 items visible with the scrollbar
- **Product List Section** 💼 
  - [x] Product List Title
  - [x] **Remove** button: Show a confirmation dialog before deleting the product
  - [x] Table listing products 
  - [x] **Product Pagination**
    - [x] Show the right amount of pages based on the product result
    - [x] Show the right product's list based on the selected page
    - [x] Table size can be selected from the footer, allowing the user to show 10, 20, 50, or 100 items per page.
  - [x] The table footer should include the page selector as indicated in the Figma design.

## Important Details
- **Notes**: [ ]
- **Considerations**: [ ]

## Attachments
**Product Management Mockup**
![Image](https://github.com/dguglielmi-git/innovandoliving/assets/54913286/25471c73-d12e-46ae-832b-b0870917a802)

**Figma source:**
https://www.figma.com/file/azVHTRldGCgKXMe6ExQiTe/Untitled?type=design&node-id=0-1&mode=design&t=tt1zl7cw0uPNpfGD-0
- Get the CSS from the Figma file by using the Figma plugin: Focus CSS.

## Tasks
- [x] [ ]
