### ISSUE TITLE
[FE] - Add/Edit a Product

### ISSUE THREAD

**Issue by dguglielmi-git** [dguglielmi-git/innovandoliving-ts#4]
## Description
We need to be able to Add a new product or edit existing ones.
Scenarios:

1. **Creating a New Product** 
  a. The user must complete the form to create a new product.
  b. If the product is successfully created in the database, the user will be redirected to the edit mode to continue uploading pictures for this new product (main and gallery pictures).
  c. If the product could not be created in the database, the user should correct the errors that prevented the creation and try saving it again.
  d. On the "Create a New Product" screen, the component for uploading pictures should not be visible.
2. **Editing a Product**
  a. The form with the data related to the product should be pre-loaded from the backend using its ID.
  b. This screen should display the component for uploading the main picture and the gallery pictures.
  c. When saving the changes, if the pictures were uploaded correctly, they should be added to the screenshots property of the product.

## Acceptance Criteria
- Form to add/edit products
 - **Required fields**:
   - Title
   - Summary
   - Category
   - Release Date
   - Price
   - Discount
   - Publish on the main screen
 - Allow main picture upload
 - When editing a product, we should see a list with the pictures we have added and we should allow CRUD options.
 - Allow multiple pictures for the media gallery of the product
 - Files must be uploaded to AWS S3 bucket

## Development Tasks
- **Product List Section** 💼 
  - [ ] **Add/Edit products**
    - [x] Create Form page for Add/Edit
      - [x] Create Add a Product Page
      - [x] Create Edit a Product Page
    - [x] Create Form Structure 
    - [x] Allow saving a product without the functionality of uploading pictures
    - [x] Add support for AWS S3 File uploading from backend and frontend
    - [x] Upload file from the frontend and save the changes
    - [x] **Add Product** button: open the form to complete the data for a new Product
    - [x] **Edit Product** button: open the same previous form but this time with all the data loaded to allow the user make some changes on the product.  
    - [x] Save button must be disabled until the form has pictures to upload or any data was modified from the form
    - [x] Save button must be disabled after running the post/put call to the backend
    - [x] Show a label "No pictures added" when there are not files in the gallery.
    - [x] On edit mode load the main picture from the URL property
    - [x] Button to remove main image
    - [ ] Add translation for all of the texts used in this component and the related ones.

## Important Details
- **Notes**: 
  - Product Management Page will be conditional rendered:
    - If the user click on **Add Product** button or trying to edit an existing product, it will render the Add/Edit form
    - When the user clicks on the **Add Product** will render the Add a new Product form
      - Save button will call to the POST endpoint for saving a new product
    - When the user clicks on the edit button within the product's table, it will render the Edit the product
      - Save button will call to the PUT endpoint for updating an existing product
    - The form will have a return button (◀ **Back**) to take the user back to the Product Management screen.
- **Considerations**: [ ]

## Links
- Use the primefaces template for uploading multiple files: https://primereact.org/fileupload/

## Attachments
**Product Add/Edit Form Mockup**
![Image](https://github.com/user-attachments/assets/befb4ae6-35d6-4f5e-8564-c261e0dd894c)

**Figma source:**
https://www.figma.com/proto/azVHTRldGCgKXMe6ExQiTe/Ecommerce?node-id=0-1&t=uTcIzt7MjNwjrc1Q-1
- Get the CSS from the Figma file by using the Figma plugin: Focus CSS.

## SubTasks
- [x] Upload Dialog for main picture
- [x] Formik structure to contain the whole Product Form
- [x] For the Edit Mode, render the picture list retrieved from the backend for the selected product
- [x] API call to the create product
- [x] API call to the update product
- [x] Connect Save button to create/update product API Call.

**Comment by dguglielmi-git** [comment]
When uploading multiple pictures and clicking on save button, is not uploading the files until the second click. Review the onSubmit function to fix some statement management issues.

**Comment by dguglielmi-git** [comment]
Now the files are being uploaded and the automatic update is working, but something is happening in the middle that is saving an id instead of the URL .

**Comment by dguglielmi-git** [comment]
We solved the issue of saving wrong urls from the backend by cleaning the list before updating the screenshots array.
What it is pending to solve is that after saving the changes the first time, the page updates and show the images uploaded in the carousel, but if we press save again, does not refresh correctly. 
The process has to be reviewed to solve this incorrect behavior.

**Comment by dguglielmi-git** [comment]
The functionality of uploading pictures and updating the product is finished. The next step is to clean the code, review if we can improve the code with some refactoring and after replacing all the hardcoded strings with translated variables the task could be closed.
